name: Deploy Telegram Bot GPT-3.5

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI openai pytesseract pillow pydub SpeechRecognition opencv-python-headless pdfminer.six

      - name: Install system dependencies
        run: sudo apt-get install -y ffmpeg

      - name: Launch bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python bot_gpt3.5/bot_gpt3.py
