name: Bot Telegramm gpt3.5

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyTelegramBotAPI openai pytesseract pillow pydub SpeechRecognition opencv-python-headless pdfminer.six
        sudo apt-get update
        sudo apt-get install -y ffmpeg

        
    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: '6069004077:AAFpxxHnaIHGWueiHh1mN9U5FkV01ntsrUM'
        OPENAI_API_KEY: "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"
      run: |
        python bot_gpt3.5/bot_gpt3.py

